### PR TITLE
fix: use specific version instead of branch dependency

### PR DESCRIPTION
**Pull request by Robbert**
When running `composer install` we got this error:

```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - phpspec/prophecy is locked to version 1.13.0 and an update of this package was not requested.
    - phpspec/prophecy 1.13.0 requires php ^7.2 || ~8.0, <8.1 -> your php version (8.1.10) does not satisfy that requirement.
  Problem 2
    - phpspec/prophecy 1.13.0 requires php ^7.2 || ~8.0, <8.1 -> your php version (8.1.10) does not satisfy that requirement.
    - phpunit/phpunit 8.5.19 requires phpspec/prophecy ^1.10.3 -> satisfiable by phpspec/prophecy[1.13.0].
    - phpunit/phpunit is locked to version 8.5.19 and an update of this package was not requested.
```

To remedy the situation we removed the lockfile (not ideal, I know) and we replaced the `"10up/wp_mock": "dev-master"` dependency with version `"~0.4"`. This is the same version as other OpenWebConcept `composer.json` files appear to use.

We included a GitHub Workflow to be able test this situation automatically in the future.

### CODE REVIEW

**Comment by Robbert** [comment]
I just noticed another similar fix was made to another repo earlier: https://github.com/OpenWebconcept/plugin-pdc-samenwerkende-catalogi/commit/5dba6aafe1497bd0e8cb00b8028d51c8d0d1816d

**Comment by mvdhoek1** [comment]
This is the right fix indeed, can jou add the version bumps as well?
- https://github.com/OpenWebconcept/plugin-pdc-base/blob/master/src/Base/Foundation/Plugin.php#L20
- https://github.com/OpenWebconcept/plugin-pdc-base/blob/master/pdc-base.php#L7
- https://github.com/OpenWebconcept/plugin-pdc-base/blob/master/CHANGELOG.md

**Comment by Robbert** [comment]
@mvdhoek1 thanks, ik zie dat je het al gefixt hebt in b4d2f6fcde1481a6d241ecf42c7496a9352ce30c

**Comment by mvdhoek1** [comment]
@Robbert klopt, n.a.v. jouw slack bericht een paar weken geleden.

**Pull request closed without merging**
